config/routes.rb
Rails.application.routes.draw do

  resources :analytics, only: :index

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  resources :promocodes
 # post 'add_promo', to: 'users#promo'
 get 'users/promo', to: 'users#promo'
 post 'add_promo', to: 'users#add_promo'
 scope "(:locale)", :locale => /en|ar/ do


# post 'promo', to: 'users#promo'
# get 'users/index'
 # collection do :users
   devise_for :users
   resources :users, only: :index

 # end



 resources :turnovers
 resources :home


 get '/about-us' => 'home#about'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/models/turnover.rb
class Turnover < ApplicationRecord
  belongs_to :user

# validates form
  validates :name_company, presence: true
  validates :position, presence: true
  validates :sallary_left, presence: true
  validates :sallart_newer, presence: true
  validates :years_lefter, presence: true
  validates :sallary_manger, presence: true
  validates :daily_hourly, presence: true
  validates :agancey_cost, presence: true
  validates :ads_cost, presence: true
  validates :sallary_HR, presence: true
  validates :spentHR_timeD, presence: true
  validates :spentHR_timeH, presence: true
  validates :oneSallary_interviewer, presence: true
  validates :onespentinterview_timeD, presence: true
  validates :onespentinterview_timeH, presence: true
  validates :twoSallary_interviewer, presence: true
  validates :twoSpentinterviewD, presence: true
  validates :twoSpentinterview_timeH, presence: true
  validates :threeSallary_interviewer, presence: true
  validates :threeSpentinterview_timeD, presence: true
  validates :threeSpentinterview_timeH, presence: true
  validates :oneSallary_admin, presence: true
  validates :oneSpentAdmin_timeD, presence: true
  validates :oneSpentAdmin_timeH, presence: true
  validates :twoSallary_admin, presence: true
  validates :twoSpentAdmin_timeD, presence: true
  validates :twoSpentAdmin_timeH, presence: true
  validates :threeSallary_admin, presence: true
  validates :threeSpentAdmin_timeD, presence: true
  validates :threeSpentAdmin_timeH, presence: true
  validates :spentSupervisor_timeD, presence: true
  validates :spentSupervisor_timeH, presence: true
  validates :spentEmployee_timeD, presence: true
  validates :spentEmployee_timeH, presence: true
  validates :Sallary_adapt, presence: true
  validates :spentadapt_timeD, presence: true
  validates :spentadapt_timeH, presence: true
  validates :sallary_trainer, presence: true
  validates :spenttrain_timeD, presence: true
  validates :spenttrain_timeH, presence: true
  validates :sallary_adminprocess, presence: true
  validates :spentprocess_timeD, presence: true
  validates :spentprocess_timeH, presence: true
  validates :sallary_adminRotenlefter, presence: true
  validates :spentRotenLefter_timeD, presence: true
  validates :spentRotenlefter_timeH, presence: true
  validates :indemnity, presence: true
  validates :balanceLeavDay_timeD, presence: true
  validates :balanceLeavDay_timeH, presence: true
  validates :Remaing_medical, presence: true


end

app/controllers/turnovers_controller.rb
class TurnoversController < ApplicationController
  before_action :authenticate_user!
  before_action :set_turnover, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  layout "turnover"

  # GET /turnovers
  # GET /turnovers.json
  def index
    @turnovers = Turnover.all
  end

  # GET /turnovers/1
  # GET /turnovers/1.json
  def show
  end

  # GET /turnovers/new
  def new
    @turnover = current_user.turnovers.build
  end

  # GET /turnovers/1/edit
  def edit
  end

  # POST /turnovers
  # POST /turnovers.json
  def create
    @turnover = current_user.turnovers.build(turnover_params)

    respond_to do |format|
      if @turnover.save
        format.html { redirect_to @turnover, notice: 'Turnover was successfully created.' }
        format.json { render :show, status: :created, location: @turnover }
      else
        format.html { render :new }
        format.json { render json: @turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnovers/1
  # PATCH/PUT /turnovers/1.json
  def update
    respond_to do |format|
      if @turnover.update(turnover_params)
        format.html { redirect_to @turnover, notice: 'Turnover was successfully updated.' }
        format.json { render :show, status: :ok, location: @turnover }
      else
        format.html { render :edit }
        format.json { render json: @turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnovers/1
  # DELETE /turnovers/1.json
  def destroy
    @turnover.destroy
    respond_to do |format|
      format.html { redirect_to turnovers_url, notice: 'Turnover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turnover
      @turnover = Turnover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turnover_params
      params.require(:turnover).permit(:name_company, :position, :sallary_left, :sallart_newer, :years_lefter, :sallary_manger, :daily_hourly, :agancey_cost, :ads_cost, :spentHR_timeH, :spentHR_timeD, :sallary_HR, :onespentinterview_timeH, :onespentinterview_timeD, :oneSallary_interviewer, :twoSpentinterview_timeH, :twoSpentinterviewD, :twoSallary_interviewer, :threeSpentinterview_timeH, :threeSpentinterview_timeD, :threeSallary_interviewer, :oneSpentAdmin_timeH, :oneSpentAdmin_timeD, :oneSallary_admin, :twoSpentAdmin_timeH, :twoSpentAdmin_timeD, :twoSallary_admin, :threeSpentAdmin_timeH, :threeSpentAdmin_timeD, :threeSallary_admin, :spentSupervisor_timeH, :spentSupervisor_timeD, :spentEmployee_timeH, :spentEmployee_timeD, :spentadapt_timeH, :spentadapt_timeD, :Sallary_adapt, :spenttrain_timeH, :spenttrain_timeD, :sallary_trainer, :spentprocess_timeH, :spentprocess_timeD, :sallary_adminprocess, :spentRotenlefter_timeH, :spentRotenLefter_timeD, :sallary_adminRotenlefter, :balanceLeavDay_timeH, :balanceLeavDay_timeD, :Remaing_medical, :indemnity)
    end
end

app/helpers/turnovers_helper.rb
module TurnoversHelper
end

app/views/turnovers/_logic.html.erb
<% @turnover.Eaa = @turnover.spentHR_timeD + @turnover.spentHR_timeH/@turnover.daily_hourly %>

<% @turnover.CostEads = @turnover.Eaa * (@turnover.sallary_HR / 30) %>

<% thirty = 30 %>
<% #All Cost Hire !  %>
<% @turnover.Ebac = @turnover.threeSpentinterview_timeD + @turnover.threeSpentinterview_timeH / @turnover.daily_hourly %>
<% @turnover.Ebab = @turnover.twoSpentinterviewD + @turnover.twoSpentinterview_timeH / @turnover.daily_hourly %>
<% @turnover.Eba = @turnover.onespentinterview_timeD + @turnover.onespentinterview_timeH / @turnover.daily_hourly %>

<% one = @turnover.Eba * (@turnover.sallary_manger / 30 ) %>
<% two = @turnover.Ebab * (@turnover.twoSallary_interviewer / 30) %>
<% three = @turnover.Ebac * (@turnover.threeSallary_interviewer/30) %>
<% @turnover.costhire = one +  two + three %>

<% #All Cost Admin !!!  %>

<% @turnover.Ecc = @turnover.oneSpentAdmin_timeD + @turnover.oneSpentAdmin_timeH / @turnover.daily_hourly %>
<% @turnover.Ecb = @turnover.twoSpentAdmin_timeD + @turnover.twoSpentAdmin_timeH / @turnover.daily_hourly %>
<% @turnover.Eca = @turnover.threeSpentAdmin_timeD + @turnover.threeSpentAdmin_timeH / @turnover.daily_hourly %>

<% one_b =  @turnover.Eca * (@turnover.oneSallary_admin/30) %>
<% two_b = @turnover.Ecb * (@turnover.twoSallary_admin/30) %>
<% three_b =  @turnover.Ecc * (@turnover.threeSallary_admin/30) %>
<% @turnover.costadmin = one_b + two_b  + three_b %>

<% # All Cost Magment %>
<% @turnover.ma = @turnover.spentSupervisor_timeD + @turnover.spentSupervisor_timeH / @turnover.daily_hourly %>
<% @turnover.costmagment = @turnover.ma * ((@turnover.sallarysupervisor.nil? ? 0 : @turnover.sallarysupervisor) / 30) %>


<% #All Cost Adapt!  %>

<% @turnover.aa = @turnover.spentEmployee_timeD + @turnover.spentEmployee_timeH / @turnover.daily_hourly %>
<% @turnover.ab = @turnover.spentadapt_timeD + @turnover.spentadapt_timeH / @turnover.daily_hourly %>
<% @turnover.ac = @turnover.spenttrain_timeD + @turnover.spenttrain_timeH / @turnover.daily_hourly %>


<% one_c =  @turnover.aa * (@turnover.sallart_newer/30) %>
<% two_c = @turnover.ab * (@turnover.Sallary_adapt/30) %>
<% three_c =  @turnover.ac * (@turnover.sallary_trainer/30) %>

<% @turnover.costadapt = one_c + two_c + three_c %>

<% # All Cost LOs contract  %>

<% @turnover.lca = @turnover.spentprocess_timeD + @turnover.spentprocess_timeH / @turnover.daily_hourly %>
<% @turnover.lcb = @turnover.spentRotenLefter_timeD + @turnover.spentRotenlefter_timeH / @turnover.daily_hourly %>
<%# @turnover.lcc = @turnover.balanceLeavDay_timeD + @turnover.balanceLeavDay_timeH / @turnover.daily_hourly %>


<% one_d =  @turnover.lca * (@turnover.sallary_adminprocess/30) %>
<% two_d = @turnover.lcb * (@turnover.sallary_adminRotenlefter/30) %>
<% three_d = @turnover.balanceLeavDay_timeD + @turnover.balanceLeavDay_timeH / @turnover.daily_hourly %>

<% @turnover.loscontract = one_d + two_d  + three_d + @turnover.Remaing_medical + @turnover.indemnity %>



<% #indirect %>



  <%  x_one = 1 * 0.50 * @turnover.sallary_left %>





<% # d_sixty in xl cheet D60   %>
<% if @turnover.years_lefter > 7 %>
<% d_sixty = 7 %>
<% else %>
<% d_sixty = @turnover.years_lefter %>

<% end %>

<% # f_sixty in xl cheet C60   %>
<% if d_sixty > 7 %>
<% f_sixty = 0.70 %>
<% else %>
<% f_sixty = d_sixty * 0.10 %>
<% end %>

  <% x_two =  f_sixty * d_sixty * @turnover.sallary_left %>

  <% x_three = 1 * 0.50 * @turnover.sallart_newer %>
  <%  x_four = 1 * 0.20 * @turnover.sallart_newer %>
  <% x_five  = 1 * 0.20 * @turnover.sallart_newer %>
  <% x_six   = 1 * 0.15 * @turnover.sallart_newer %>
  <% x_seven = 1 * 0.20 * @turnover.sallary_manger %>
  <% x_eight = 3 * 0.50 * @turnover.sallart_newer %>
  <% x_nine  = 1 * 0.10 * @turnover.sallart_newer%>

<% #SUM(F59:F67) %>

  <% @turnover.indirect_cost = x_one + x_two + x_three + x_four + x_five + x_six + x_seven + x_eight + x_nine %>

  <% # TurnOver %>
  <% turnover_decimal = @turnover.agancey_cost + @turnover.ads_cost + @turnover.CostEads + @turnover.costhire + @turnover.costadmin + @turnover.costmagment + @turnover.costadapt + @turnover.loscontract + @turnover.indirect_cost %>

<% @turnover.turnover_ratio = (turnover_decimal / @turnover.sallary_left).to_i %>

app/views/turnovers/edit.html.erb
<h1>Editing Turnover</h1>

<%= render 'form', turnover: @turnover %>

<%= link_to 'Show', @turnover %> |
<%= link_to 'Back', turnovers_path %>

app/views/turnovers/index.html.erb
<% if current_user.admin == true %>



<p id="notice"><%= notice %></p>

<h1>Turnovers</h1>

<table>
  <thead>
    <tr>
      <th>Name company</th>
      <th>Position</th>
      <th>Sallary left</th>
      <th>Sallart newer</th>
      <th>Years lefter</th>
      <th>Sallary manger</th>
      <th>Daily hourly</th>
      <th>Agancey cost</th>
      <th>Ads cost</th>
      <th>Spenthr timeh</th>
      <th>Spenthr timed</th>
      <th>Sallary hr</th>
      <th>Onespentinterview timeh</th>
      <th>Onespentinterview timed</th>
      <th>Onesallary interviewer</th>
      <th>Twospentinterview timeh</th>
      <th>Twospentinterviewd</th>
      <th>Twosallary interviewer</th>
      <th>Threespentinterview timeh</th>
      <th>Threespentinterview timed</th>
      <th>Threesallary interviewer</th>
      <th>Onespentadmin timeh</th>
      <th>Onespentadmin timed</th>
      <th>Onesallary admin</th>
      <th>Twospentadmin timeh</th>
      <th>Twospentadmin timed</th>
      <th>Twosallary admin</th>
      <th>Threespentadmin timeh</th>
      <th>Threespentadmin timed</th>
      <th>Threesallary admin</th>
      <th>Spentsupervisor timeh</th>
      <th>Spentsupervisor timed</th>
      <th>Spentemployee timeh</th>
      <th>Spentemployee timed</th>
      <th>Spentadapt timeh</th>
      <th>Spentadapt timed</th>
      <th>Sallary adapt</th>
      <th>Spenttrain timeh</th>
      <th>Spenttrain timed</th>
      <th>Sallary trainer</th>
      <th>Spentprocess timeh</th>
      <th>Spentprocess timed</th>
      <th>Sallary adminprocess</th>
      <th>Spentrotenlefter timeh</th>
      <th>Spentrotenlefter timed</th>
      <th>Sallary adminrotenlefter</th>
      <th>Balanceleavday timeh</th>
      <th>Balanceleavday timed</th>
      <th>Remaing medical</th>
      <th>Indemnity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnovers.each do |turnover| %>
      <tr>
        <td><%= turnover.name_company %></td>
        <td><%= turnover.position %></td>
        <td><%= turnover.sallary_left %></td>
        <td><%= turnover.sallart_newer %></td>
        <td><%= turnover.years_lefter %></td>
        <td><%= turnover.sallary_manger %></td>
        <td><%= turnover.daily_hourly %></td>
        <td><%= turnover.agancey_cost %></td>
        <td><%= turnover.ads_cost %></td>
        <td><%= turnover.spentHR_timeH %></td>
        <td><%= turnover.spentHR_timeD %></td>
        <td><%= turnover.sallary_HR %></td>
        <td><%= turnover.onespentinterview_timeH %></td>
        <td><%= turnover.onespentinterview_timeD %></td>
        <td><%= turnover.oneSallary_interviewer %></td>
        <td><%= turnover.twoSpentinterview_timeH %></td>
        <td><%= turnover.twoSpentinterviewD %></td>
        <td><%= turnover.twoSallary_interviewer %></td>
        <td><%= turnover.threeSpentinterview_timeH %></td>
        <td><%= turnover.threeSpentinterview_timeD %></td>
        <td><%= turnover.threeSallary_interviewer %></td>
        <td><%= turnover.oneSpentAdmin_timeH %></td>
        <td><%= turnover.oneSpentAdmin_timeD %></td>
        <td><%= turnover.oneSallary_admin %></td>
        <td><%= turnover.twoSpentAdmin_timeH %></td>
        <td><%= turnover.twoSpentAdmin_timeD %></td>
        <td><%= turnover.twoSallary_admin %></td>
        <td><%= turnover.threeSpentAdmin_timeH %></td>
        <td><%= turnover.threeSpentAdmin_timeD %></td>
        <td><%= turnover.threeSallary_admin %></td>
        <td><%= turnover.spentSupervisor_timeH %></td>
        <td><%= turnover.spentSupervisor_timeD %></td>
        <td><%= turnover.spentEmployee_timeH %></td>
        <td><%= turnover.spentEmployee_timeD %></td>
        <td><%= turnover.spentadapt_timeH %></td>
        <td><%= turnover.spentadapt_timeD %></td>
        <td><%= turnover.Sallary_adapt %></td>
        <td><%= turnover.spenttrain_timeH %></td>
        <td><%= turnover.spenttrain_timeD %></td>
        <td><%= turnover.sallary_trainer %></td>
        <td><%= turnover.spentprocess_timeH %></td>
        <td><%= turnover.spentprocess_timeD %></td>
        <td><%= turnover.sallary_adminprocess %></td>
        <td><%= turnover.spentRotenlefter_timeH %></td>
        <td><%= turnover.spentRotenLefter_timeD %></td>
        <td><%= turnover.sallary_adminRotenlefter %></td>
        <td><%= turnover.balanceLeavDay_timeH %></td>
        <td><%= turnover.balanceLeavDay_timeD %></td>
        <td><%= turnover.Remaing_medical %></td>
        <td><%= turnover.indemnity %></td>
        <td><%= link_to 'Show', turnover %></td>
        <td><%= link_to 'Edit', edit_turnover_path(turnover) %></td>
        <td><%= link_to 'Destroy', turnover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turnover', new_turnover_path %>
<% else %>
Not found !!!
<% end %>

app/views/turnovers/new.html.erb
<% if current_user.turnovers.count == 3 %>
<p> put your promocodes <%= link_to 'Here' , users_promo_url %> </p>
<% else %>
<%= render 'form', turnover: @turnover %>
<% end %>
<%= link_to 'Back', turnovers_path %>

app/views/turnovers/show.html.erb
<% if can? :update, @turnover %>
<%= render 'logic', turnover: @turnover %>

<div class="row">
        <div class="col l12 s12 m12 logo">
          <%= link_to root_path do %>
<%= image_tag("Group-3.png" , class:"responsive-img") %>
<% end %>
        </div>
    </div>
    <div class="row result-body">
        <div class="container">
            <h3>Your result</h3>
            <div class="data col l12 m12 s12">
                <div class="col l6 m12 s12 result ">
                    <p class="head-title">Total direct costs</p>
                    <p class="data-val">   <%= (@turnover.agancey_cost + @turnover.ads_cost + @turnover.CostEads + @turnover.costhire + @turnover.costadmin + @turnover.costmagment + @turnover.costadapt +  @turnover.loscontract).round %>
 </p>
                    <span>EGP</span>
                    <p class="head-title">Total indirect costs</p>
                    <p class="data-val">  <%= @turnover.indirect_cost %>
 </p>
                    <span>EGP</span>
                    <p class="head-title">% Cost oF Turnover</p>
                    <p class="data-val">    <%= @turnover.turnover_ratio.to_i %>
%</p> <br>
<%= link_to 'New turnover', new_turnover_path , class: "waves-effect waves-light btn get-started" %>

                </div>
            </div>
        </div>
    </div>



    <%= @turnover.agancey_cost  %> <br> |
<%= @turnover.ads_cost %>|
<%= @turnover.CostEads %>|
<%= @turnover.costhire %>|
<%=  @turnover.costadmin %>|
<%=  @turnover.costadapt %> |
<%= @turnover.loscontract %>
<%= link_to 'Edit', edit_turnover_path(@turnover) %> |
<%= link_to 'Back', turnovers_path %>
<% else %>
Not found !
<% end %>