config/routes.rb
Rails.application.routes.draw do

  resources :analytics, only: :index

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  resources :promocodes
 # post 'add_promo', to: 'users#promo'
 get 'users/promo', to: 'users#promo'
 post 'add_promo', to: 'users#add_promo'
 scope "(:locale)", :locale => /en|ar/ do


# post 'promo', to: 'users#promo'
# get 'users/index'
 # collection do :users
   devise_for :users
   resources :users, only: :index

 # end



 resources :turnovers
 resources :home


 get '/about-us' => 'home#about'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"
  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def index

  end

  def about

  end

def resource_name
  :user
end

def resource
  @resource ||= User.new
end

def resource_class
  User
end

def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_facts.html.erb
<div id="gtco-counter" class="gtco-section">
  <div class="gtco-container">

    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
        <h2>Fun Facts</h2>
        <p>Some stats about our customers.</p>
      </div>
    </div>

    <div class="row">

      <div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
        <div class="feature-center">
          <span class="icon">
            <i class="ti-settings"></i>
          </span>
          <span class="counter js-counter" data-from="0" data-to="22070" data-speed="5000" data-refresh-interval="50">1</span>
          <span class="counter-label">Creativity Fuel</span>

        </div>
      </div>
      <div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
        <div class="feature-center">
          <span class="icon">
            <i class="ti-face-smile"></i>
          </span>
          <span class="counter js-counter" data-from="0" data-to="97" data-speed="5000" data-refresh-interval="50">1</span>
          <span class="counter-label">Happy Clients</span>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
        <div class="feature-center">
          <span class="icon">
            <i class="ti-briefcase"></i>
          </span>
          <span class="counter js-counter" data-from="0" data-to="402" data-speed="5000" data-refresh-interval="50">1</span>
          <span class="counter-label">Projects Done</span>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
        <div class="feature-center">
          <span class="icon">
            <i class="ti-time"></i>
          </span>
          <span class="counter js-counter" data-from="0" data-to="212023" data-speed="5000" data-refresh-interval="50">1</span>
          <span class="counter-label">Hours Spent</span>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/home/_features.html.erb
	<div id="gtco-features">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2><%= t('turnover_features') %></h2>
					<p><%= t('features_detials') %></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 col-sm-6">
					<div class="feature-center animate-box" data-animate-effect="fadeIn">
						<span class="icon">
							<i class="fa fa-shield"></i>
						</span>
						<h3><%= t('very_secure') %></h3>
						<p><%= t('secure_detials') %> </p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="feature-center animate-box" data-animate-effect="fadeIn">
						<span class="icon">
							<i class="fa fa-money"></i>
						</span>
						<h3><%= t('save_money') %></h3>
						<p><%= t('money_detials') %></p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="feature-center animate-box" data-animate-effect="fadeIn">
						<span class="icon">
							<i class="fa fa-cog"></i>
						</span>
						<h3><%= t('more_flexibility') %> </h3>
						<p><%= t('flexibility_detials') %>  </p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="feature-center animate-box" data-animate-effect="fadeIn">
						<span class="icon">
							<i class="fa fa-clock-o"></i>
						</span>
						<h3><%= t('save_time') %> </h3>
						<p><%= t('time_detials') %> </p>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/home/_footer.html.erb
<footer id="gtco-footer" role="contentinfo">
  <div class="gtco-container">
    <div class="row row-p	b-md">

      <div class="col-md-4">
        <div class="gtco-widget">
          <h3>About Us</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore eos molestias quod sint ipsum possimus temporibus officia iste perspiciatis consectetur in fugiat repudiandae cum. Totam cupiditate nostrum ut neque ab?</p>
        </div>
      </div>

      <div class="col-md-4 col-md-push-1">
        <div class="gtco-widget">
          <h3>Links</h3>
          <ul class="gtco-footer-links">
            <li><a href="#">Knowledge Base</a></li>
            <li><a href="#">Career</a></li>
            <li><a href="#">Press</a></li>
            <li><a href="#">Terms of services</a></li>
            <li><a href="#">Privacy Policy</a></li>
          </ul>
        </div>
      </div>

      <div class="col-md-4">
        <div class="gtco-widget">
          <h3>Get In Touch</h3>
          <ul class="gtco-quick-contact">
            <li><a href="#"><i class="icon-phone"></i> +1 234 567 890</a></li>
            <li><a href="#"><i class="icon-mail2"></i> info@fedamisr.net</a></li>
            <li><a href="#"><i class="icon-chat"></i> Live Chat</a></li>
          </ul>
        </div>
      </div>

    </div>

    <div class="row copyright">
      <div class="col-md-12">
        <p class="pull-left">
        </p>
        <p class="pull-right">
          <ul class="gtco-social-icons pull-right">
            <li><a href="#"><i class="icon-twitter"></i></a></li>
            <li><a href="#"><i class="icon-facebook"></i></a></li>
            <li><a href="#"><i class="icon-linkedin"></i></a></li>
            <li><a href="#"><i class="icon-dribbble"></i></a></li>
          </ul>
        </p>
      </div>
    </div>

  </div>
</footer>
</div>

<div class="gototop js-top">
  <a href="#" class="js-gotop"><i class="fa fa-chevron-circle-up"></i></a>
</div>

app/views/home/_nav.html.erb
<nav class="gtco-nav" role="navigation">
  <div class="gtco-container">
    <div class="row">
      <div class="col-md-12 text-right gtco-contact">
        <ul class="">
          <li><a href="#"><i class="fa fa-phone"></i> 00000 </a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 col-xs-12">
        <div id="gtco-logo"><%= link_to t('name_app') , root_url %> <em>.</em></a></div>
      </div>
      <div class="col-xs-8 text-right menu-1">
        <ul>
          <li class="active"><%= link_to t('home') , root_url %></li>
          <!-- <li><a href="about.html">About</a></li> -->

          <% if user_signed_in? %>
         <li>
           <%= link_to t('logout'), destroy_user_session_path  , method: :delete %>
        </li>
        <%  if  current_user.productowner == true %>

       <%= link_to t('ProductOwner Dashbord'), analytics_url  %>
        <% end %>

         <% else %>
         <li>
         <%= link_to t('signup'), new_user_registration_path  %>
        </li>

       <li>
       <%= link_to t('login'), new_user_session_path  %>
       </li>

        <% end %>
              <li>
       <%= link_to "About Us", about_us_url %>

       </li>
       <% if I18n.locale == I18n.default_locale %>
       <li>
       <%= link_to "عربي", '/ar' %>
       </li>
       <% else %>
       <li>
       <%= link_to "English", '/en' %>

       </li>
       <%end%>

        </ul>
      </div>
    </div>

  </div>
</nav>

app/views/home/about.html.erb
<div class="gtco-loader"></div>

	<div id="page">
<%= render 'nav' %>
	<header id="gtco-header" class="gtco-cover gtco-cover-xs" role="banner" style="background-image:url(images/img_bg_1.jpg);">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc">
							<h1 class="animate-box" data-animate-effect="fadeInUp">About Us</h1>
						<!--	<h2 class="animate-box" data-animate-effect="fadeInUp">Free HTML5 Bootstrap Templates Made <em>by</em> <a href="http://gettemplates.co/" target="_blank">GetTemplates.co</a></h2>
					-->	</div>
					</div>
				</div>
			</div>
		</div>
	</header>

	<div id="gtco-history" class="gtco-section border-bottom animate-box">
		<div class="gtco-container">

			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Company History</h2>
					<p>

الخلفية

يجري تنفيذ مشروع الوصول إلى سوق العمل (LMAP) بالنيابة عن الوزارة الاتحادية الألمانية للتعاون الاقتصادي والتنمية (BMZ) عن طريق التعاون الدولي الألمانى (GIZ) و يهدف هذا المشروع الي تحسين فرص العمل للشباب في مصر، لا سيما في المجال غير الأكاديمي، وذلك عن طريق إنشاء خدمات التوظيف التي تقدم التوجيه الوظيفي، ومطابقة الوظائف والتوظيف؛ وعن طريق تحسين جودة عملية التوظي. ويهدف مجال النشاط 2 من المشروع الي تحسين جودة الوظائف فى الشركات الصغيرة والمتوسطة وذلك بالتعاون مع اتحاد جمعيات التنمية الاقتصادية (FEDA).

أسباب تطوير الاداة الخاصة بحساب تكلفة دوران العمالة

تفتقد معظم الشركات الي المعلومات الخاصة بتكلفة دوران وتسرب العمالة مما يؤدي الي الاحجام في بعض الاحيان عن تنفيذ التدخلات الخاصة بالحفاظ علي العمالة نظرا لغياب الارقام التقريبية والتقديرية والتي من الممكن ان تحفز صاحب القرار بالشركة علي تحسين ظروف العمل وتقديم جودة افضل للوظائف المعروضة. والجديد في تنفيذ تلك الاداة هو حساب التكلفة الغير مباشرة بالاضافة الي التكلفة المباشرة بطبيعة الحال. حيث تعتبر االتكلفة الغير مباشرة هي من اكثر العوامل التي تؤدي الي ارتفاع تكلفة معدل تسرب العمالة والتي من ثم تؤثر بشكل مباشرعلي تكاليف العملية الانتاجية و بالتبعية علي معدل الربحية . ويهدف التعاون بين مشروع الوصول إلى سوق العمل (LMAP) ومشروع تعزيز حقوق العمال والقدرة التنافسية للصناعات التصديرية في مصر–منظمة العمل الدولية (ILO) الي تصميم اداة علمية ذات دقة تتراوح ما بين 75 - 80 % تقوم بحساب التكلفة المباشرة والتي لا تجد الشركات صعوبة في حسابها وأيضا التكاليف الغير مباشرة والتي تعتبر احد التحديات في مجال تطوير الاداء الخاص بنظم الموارد البشرية بالشركات.

والتي تتضمن بعض النقاط التالية:

- حساب التكلفة الفعلية لعملية تعيين العامل

- حساب التكلفة الفعلية لعملية تغطية تسرب العامل وتوزيع المهام علي عمال اخرين للحفاظ علي معدلات الانتاج

- تكلفة تعيين عامل اخرجديد

- تكلفة توعية وتدريب العامل الجديد

- تكلفة الانخفاض في معدلات الانتاج نتيجة فرق الخبرات بين العامل المتسرب والعامل الجديد حتي علي افتراض التساوي

في الخبرات. بالاضافة الي بعض التأثيرات الاخري والتي فد تختلف من صناعة لاخري.

تهدف هذه الاداة الي توفير مؤشر مالي واضح لاصحاب الاعمال حول تكلفة معدل تسرب العمالة يمكنهم من التحقق واتخاذ القرارات المتعلقة بالتدخلات الخاصة بتحسين بيئة العمل وأيضا لتحسين جودة الوظائف من خلال تطبيق الممارسات الصحيحة لتنمية وادارة استراتيجيات الموارد البشرية. </p>
				</div>
			</div>

      <%= render 'footer' %>

app/views/home/index.html.erb
<div class="gtco-loader"></div>

	<div id="page">
<%= render 'nav' %>
	<header id="gtco-header" class="gtco-cover" role="banner" style="background-image:url(images/img_bg_1.jpg);">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="display-t">
						<div class="display-tc">
							<h1 class="animate-box" data-animate-effect="fadeInUp"><%= t('bref_home') %></h1>
							<!-- <h2 class="animate-box" data-animate-effect="fadeInUp">To see more detials Click <a href="#" target="_blank">Here</a></h2> -->
							<!-- <p class="animate-box" data-animate-effect="fadeInUp"><a href="#" class="btn btn-white btn-lg btn-outline">Get In Touch</a></p> -->
							<% if user_signed_in? %>

						   <%= link_to t('start_now'), new_turnover_path , class: "animate-box btn btn-white btn-lg btn-outline"  %>
               <% end %>

						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

<%= render 'features' %>

<%= render 'footer' %>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
<%  end %>

<!--


<div class="row ">
       <div class="container">
           <div class="col l12 s12 m12 nav">
               <div class="left col l6 m6 s12">
                   <a href="#">
                    <%= image_tag("logo.png", class: "menu_icon") %>

                   </a>
                   <p class="logoData"><%= t('name_app') %></p>
               </div>
               <div class="right col l6 m6 s12">
<ul>
                 <% if user_signed_in? %>
                 <li>
                   <%= link_to t('logout'), destroy_user_session_path,class: "waves-effect waves-light btn modal-trigger" , method: :delete %>
                </li>
                 <% else %>
                 <li>
                 <%= link_to t('signup'), new_user_registration_path , class: "waves-effect waves-light btn modal-trigger" %>
               </li>

<li>
 <%= link_to t('login'), new_user_session_path , class: "waves-effect waves-light btn modal-trigger" %>
</li>



 <% end %>
 <% if I18n.locale == I18n.default_locale %>
 <li>
   <%= link_to "عربي", '/ar', class: "waves-effect waves-light btn modal-trigger" %>
 </li>
 <% else %>
 <li>
   <%= link_to "English", '/en', class: "waves-effect waves-light btn modal-trigger" %>

 </li>
 <%end%>
</ul>
               </div>
           </div>
       </div>
   </div>
   <!-- Modal Structure -->

   <!-- <div class="row">
       <div class="container">
           <div class="col s12">
             <%= image_tag("char1.png", class: "character") %>

               <h3 class="short-desc"><%= t('head_title_home') %></h3>
               <p class="details"><%= t('bref_home') %></p>
 <% if user_signed_in? %>
                <%= link_to 'Get started now', new_turnover_path , class: "waves-effect waves-light btn get-started" %>

 <% end %>


           </div>
       </div>
   </div>
   <div class="row partners">
       <div class="container">
           <div class="col l12 s12 m12">
               <a href="">
                 <%= image_tag("partners/partn1.png") %>

               </a>
               <a href="">
                 <%= image_tag("partners/partn2.png") %>
               </a>
               <a href="">
                 <%= image_tag("partners/partn3.png") %>
               </a>
               <a href="">
                 <%= image_tag("partners/partn4.png") %>
               </a>
           </div>
       </div>
   </div> -->