config/routes.rb
Rails.application.routes.draw do

  resources :analytics, only: :index

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  resources :promocodes
 # post 'add_promo', to: 'users#promo'
 get 'users/promo', to: 'users#promo'
 post 'add_promo', to: 'users#add_promo'
 scope "(:locale)", :locale => /en|ar/ do


# post 'promo', to: 'users#promo'
# get 'users/index'
 # collection do :users
   devise_for :users
   resources :users, only: :index

 # end



 resources :turnovers
 resources :home


 get '/about-us' => 'home#about'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/models/promocode.rb
class Promocode < ApplicationRecord
  # validates
   validates :code, presence: true
   validates :credit, presence: true
   validates :limitations_use, presence: true

#


 has_and_belongs_to_many :users
end

app/controllers/promocodes_controller.rb
class PromocodesController < ApplicationController
  before_action :set_promocode, only: [:show, :edit, :update, :destroy]

  # GET /promocodes
  # GET /promocodes.json
  def index
    @promocodes = Promocode.all
  end

  # GET /promocodes/1
  # GET /promocodes/1.json
  def show
  end

  # GET /promocodes/new
  def new
    @promocode = Promocode.new
  end

  # GET /promocodes/1/edit
  def edit
  end

  # POST /promocodes
  # POST /promocodes.json
  def create
    @promocode = Promocode.new(promocode_params)

    respond_to do |format|
      if @promocode.save
        format.html { redirect_to @promocode, notice: 'Promocode was successfully created.' }
        format.json { render :show, status: :created, location: @promocode }
      else
        format.html { render :new }
        format.json { render json: @promocode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocodes/1
  # PATCH/PUT /promocodes/1.json
  def update
    respond_to do |format|
      if @promocode.update(promocode_params)
        format.html { redirect_to @promocode, notice: 'Promocode was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocode }
      else
        format.html { render :edit }
        format.json { render json: @promocode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocodes/1
  # DELETE /promocodes/1.json
  def destroy
    @promocode.destroy
    respond_to do |format|
      format.html { redirect_to promocodes_url, notice: 'Promocode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def set_promocode
      @promocode = Promocode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promocode_params
      params.require(:promocode).permit(:code, :credit, :limitations_use)
    end
end

app/helpers/promocodes_helper.rb
module PromocodesHelper
end

app/views/promocodes/_form.html.erb
<%= form_with(model: promocode, local: true) do |form| %>
  <% if promocode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promocode.errors.count, "error") %> prohibited this promocode from being saved:</h2>

      <ul>
      <% promocode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :promocode_code %>
  </div>

  <div class="field">
    <%= form.label :credit %>
    <%= form.number_field :credit, id: :promocode_credit %>
  </div>

  <div class="field">
    <%= form.label :limitations_use %>
    <%= form.number_field :limitations_use, id: :promocode_limitations_use %>
  </div>

  <div class="actions">

    <%= form.submit %>
  </div>
<% end %>

app/views/promocodes/edit.html.erb
<h1>Editing Promocode</h1>

<%= render 'form', promocode: @promocode %>

<%= link_to 'Show', @promocode %> |
<%= link_to 'Back', promocodes_path %>

app/views/promocodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Promocodes</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Credit</th>
      <th>Limitations use</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promocodes.each do |promocode| %>
      <tr>
        <td><%= promocode.code %></td>
        <td><%= promocode.credit %></td>
        <td><%= promocode.limitations_use %></td>
        <td><%= link_to 'Show', promocode %></td>
        <td><%= link_to 'Edit', edit_promocode_path(promocode) %></td>
        <td><%= link_to 'Destroy', promocode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promocode', new_promocode_path %>

app/views/promocodes/new.html.erb
<h1>New Promocode</h1>

<%= render 'form', promocode: @promocode %>

<%= link_to 'Back', promocodes_path %>

app/views/promocodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @promocode.code %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @promocode.credit %>
</p>

<p>
  <strong>Limitations use:</strong>
  <%= @promocode.limitations_use %>
</p>

<%= link_to 'Edit', edit_promocode_path(@promocode) %> |
<%= link_to 'Back', promocodes_path %>